trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# ADD KUBECTL TASK
- task: Kubernetes@1
  displayName: 'Deploy to Kubernetes cluster'
  inputs:
    connectionType: 'Kubernetes Service Connection'  # or 'Azure Resource Manager'
    kubernetesServiceEndpoint: 'self-created-cluster' # Set this in Azure DevOps
    namespace: default
    command: apply
    arguments: '-f deploymentservice.yaml'

